### ISSUE TITLE
Create list of learning resources for students

### ISSUE THREAD

**Issue by damienomurchu** [laurafitzgerald/student-help-guide#7]
Create a markdown document in repo listing various learning resources that may be used by students. 

Suggestions: 
- introductory learning books
- introductory tutorials (especially offline ones)
- links to basics guides (ie basic git/ W3Schools/ etc)

@laurafitzgerald @JameelB @lgriffin just pinging you on this so you can flag any resources you think would be helpful

**Comment by JameelB** [comment]
[Get Coding!](http://getcodingkids.com), [Code Academy](https://www.codecademy.com/), [Free Code Camp](https://www.freecodecamp.org/)
