### ISSUE TITLE
Create lesson plan for first 4 weeks

### ISSUE THREAD

**Issue by damienomurchu** [laurafitzgerald/student-help-guide#8]
Discuss and decide the program for the first 4 weeks

@lgriffin @laurafitzgerald @JameelB just pinging you on this - we can discuss in comments here if you want

**Comment by lgriffin** [comment]
# Week 1: Induction

* Site walk around with Aoife for health and safety

* Identify and assign a long term buddy for coffee / lunch -- note we need to do this when sending the HR letter. Suggesting it is the 3 of you tagged here and maybe one more person from Eng. I don't want to put Brendan and I in as a long term buddy when we are heavy on meetings.

* Laptop setup: Setup a Gmail account for them (for gdocs) and a Github Account

* Presentation and walkthrough of the goals of the placement, the rules that we are enforcing (homework, coding club, diary, Coder Dojo etc.)

* Some form of a document for them to read about coding etc. TBD here.


# Week 2:

* Introduction to MarkDown (Paul would be best for this)

* First Blog Post of their work experience in Markdown

* Brain Dump of features for the School Website in Markdown

* Homework: Collaboratively write a guide in MarkDown for the Schools Coding Club

# Week 3:

* Requirements elicitation with Brendan and Chris Foley

* Come up with Personas for who will use it (student, parent, teacher, admin)

* User Story Writing to start capturing the brain dump into requirements


# Week 4:

* Introduction to the concept of Wireframes (Brid or David Ffrench here)

* Pen and paper / white board drawings of the homepage based on user stories they generated

* Homework: Wireframe up 2-3 other screens per student

# Week 5:

* Introduction to HTML / CSS

* Potential Homework: Github.io page with their CV created on it maybe in Markdown now

# Weeks 6-8:

* More HTML / CSS work

* Take one of the wireframes and implement it

* More Homework: CV wrote in HTML now and on Github.io

That's not a bad start and covers the first 2 months in my head. Thoughts?

**Comment by damienomurchu** [comment]
Think this is a really good start

Of the top of my head, I think there should be some practical coding from week 1, whether that's an intro to codecademy/ freecodecamp/ some intro programming exercises

**Comment by lgriffin** [comment]
I'd like to explore a coding option and a non coding option. One thing I want them to get from the placement is how much non coding prep goes into actual coding if you get me. So them having a gentle introduction to coding is great, I don't want that to become the focal point. We all get tunnel vision when trying to solve a problem and more so when learning a new language. I could foresee a difficulty if we exposed them to too much coding initially and try to claw that back with "boring" work. A healthy balance would be great!
